apiVersion: v1
kind: Service
metadata:
  name: servicio1
  labels:
    app: servicio1
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: http
      port: 8085
      targetPort: 8090
      nodePort: 30089
      protocol: TCP 